### ISSUE TITLE
Course restructure part 1 - basic

### ISSUE THREAD

**Issue by dandavies99** [ImperialCollegeLondon/introductory_grad_school_git_course#1]
# Overview

This is the main issue to coordinate restructuring of this course into the Basic course. A separate issue will deal with the ✨ new ✨  intermediate course.

Proposed title of this course: **Introduction to using Git and GitHub for software development**

## Rough course timings

**To be reviewed**

0. Setup: 0 min
1. Why use version control: 10 min  
2. Committing and History: 50 min
3. Sharing your code: 20 min
4. Remote repositories: 40 min
5. GUIs and IDEs: 20 min
6. Using GitHub Issues to manage your ToDo list in relation to the software: 30 min

**Total ~= 2hr 50 hr without factoring in breaks**

# Development workflow

I suggest we branch from and merge into the [basic_course branch](https://github.com/ImperialCollegeLondon/grad_school_git_course/tree/basic_course) so as not to disrupt courses that are going on during development. 

# Individual tasks 

- [ ] ImperialCollegeLondon/grad_school_git_course#36
- [ ] ImperialCollegeLondon/grad_school_git_course#37
- [ ] ImperialCollegeLondon/grad_school_git_course#38
- [ ] ImperialCollegeLondon/grad_school_git_course#40
- [ ] ImperialCollegeLondon/grad_school_git_course#35

After the above main tasks have been performed: 
- [ ] ImperialCollegeLondon/grad_school_git_course#39
